### ISSUE TITLE
Fails to Launch

### ISSUE THREAD

**Issue by TarkusLee** [odabugs/kof-combo-hitboxes#1]
Windows 10:
Error occurred  inside Lua script: ...X Accent Core Plus R\lua\game\steam\ggxxacplusr\game.lua:3: loop or previous error loading module 'game.steam.ggxxacplusr.game'
stack traceback:
    [C]: in fucntion 'rquire'
    ....X Accent Core Plus R\lua\game\steam\ggxxacplusr\game.lua:3: in main chunk
    [C]: in fucntion 'rquire'
    ....mon\Guilty Gear XX Accent Core Plus R\lua\detectgame.lua:283: in function 'moduleForGame'
    lua/main.lua:43: in function <lua/main.lua:38>

**Comment by odabugs** [comment]
Testing notes: This issue seems to occur when the path to kof-hitboxes.exe includes spaces in any of the directory names.  This appears to be a limitation of Lua's built-in "require" function, so it will require further investigation to find a way around this issue.

**Comment by alexsharoff** [comment]
In the latest release (1.0.3) lua/game/steam/ggxxacplusr/game.lua content is incorrect, it's a copy of lua/game/steam/ggxxreload/game.lua for some reason.

**Comment by odabugs** [comment]
Thank you for spotting this.  I just uploaded a corrected version of kof-combo-hitboxes-1.0.3.zip.  The earlier note about the tool failing to start when run from directory paths that contain spaces seems to have been a red herring (I tried just now and it worked for me), so I'm marking this resolved now.
